# Generated by Django 5.0 on 2024-01-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_merchant', '0005_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
