# Generated by Django 5.0 on 2024-01-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_merchant', '0006_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
